// Counting DNA Nucleotides

package main

import "fmt"

//import "os"

func main() {
	x := os.Args[1]
	//x := "AGTGAACCAGCCTAACTCCTTTGTGAGCATCATAACTCAGCTACGTAATGCCTCCTGTGCGTGACCCCTTCTGCAGCGACGCATATAGGGGGACGTCGCGCTCCGATTCAACCCAGGAGTACCGACGCCGCCCAACGGCCTTTCCACACTTCTCTCGTACCGGACCTCTTTCACTTCGTGATGGATACTATGTCCATGACCCTCGCCCCCTCGGTACCCTAGATAATTGTCGTGAGTGCCGTCAAACGCTTATTGTTGGCAACCCCGAGATAGAGTCTAAGCGAAGAAGCTTTGGTTTCATGCGAGGGTCTCGACGGATAGCTAGTACGACGGGGAGGCTGAGGCGTAATGAGAGATGCATGGCTTTTCGACGCATGCACAGATCGGGTGAATTGCCGGTCGGTGTAAGTTTTAGGCAGTAGTAGTGACTTGGCAACCATAATCCCGGTAAACCTAAAGCAATGTCAATGACGTCCAGGACCCACCGCCTTGACGGCTTTTCAGAAGCAACTGTCGGGACGCTTGTGTGAGCTTAGGGCCTCACTCTCTATTCCTGGTTGGCAAGGTATCCATTAAGGCAGCGCAAGAAAGTTAACGCGTGCAGCCACGTATTGGGTTCACATTAATATTTTGTGTAAATAATTCACGTATCTGCCTTACCCCTGCCCATCGCCTGCGCATGAGGCCAAGTAAACGGGCTATAACTCCACAGACCTCGACCCCTGCCATTAAGGGTATTCTTCGGTTATGATGGGTCAAAAAATTTGAGAAGTTATGACCAGTGTAAATCCGCCCAGAAGAGAATATTAAAGCAACTTTAGAACGGCTCGGTGGCGTTCTGCTTGTAATCATGAACCGCGGATAGATTAACATCGACCGTCAAAGCCCCTTTGGTCAGATCATTAGGATGCAGTTACTCTAAGAATGAGCTGTACTCTGGACATTTCGCACCAACACCCGAAGAACCGCGCTAAAAGTCCGATTCACAC"
	var count [256]int
	for _, letter := range x {
		count[letter]++
	}
	for i, letter := range []byte{'A', 'C', 'G', 'T'} {
		if i != 0 {
			fmt.Print(" ")
		}
		fmt.Print(count[letter])
	}
	fmt.Print("\n")
}
