// given two strings s and t, t is a substring of s
// find out the position of t in s
// sample input GATATATGCATATACTT  ATAT  output:2 4 10

package main

import (
	"fmt"
	//"os"
)

func main() {
	// read file into it
	//s, err := os.Open("file.go")
	//if err != nil {
	//	log.Fatal(err)
	//}
	s := "GTGAAAAATGAAAAAGGTGAAAAAGTTGAAAAAATTGAAAAAGTGAAAAACTGAAAAAGAATGAAAAAGGCAGAGACTGAAAAATTGAAAAATGATGAAAAAAGCGATGAAAAAAATTGAAAAACTTGAAAAACTTGAAAAACAAGTGAAAAACAGTGAAAAAGGTGAAAAAGATCTGAAAAAAGTATGAAAAAGTGAAAAAACTGAAAAACGCTGAAAAATCGTGAAAAACGCGATGAAAAATGAAAAATGAAAAAGTGAAAAAAGTAATTGAAAAATCAGAGCAATGAAAAATGAAAAATGAAAAATGAAAAATGAAAAATGAAAAATGAAAAACCTGTGAAAAAATGAAAAATGAAAAAGTTCTCATGAAAAATGAAAAATGAAAAATGAAAAACGATGGTGAAAAAAAGCATGAAAAATTGAAAAATGAAAAAAAGCATGATGAAAAACTAGTGAAAAAGCTGAAAAATGTTTGAAAAAAATGAAAAAGTGAAAAAGTTTGAAAAAGGAGTGAAAAACTGAAAAATGTGAAAAACGTTGAAAAACGGTGAAAAATGAAAAAGTTGAAAAACCCGTGAAAAAATGAAAAAATGAAAAACCTGGATTGAAAAATGAAAAAAGTGAAAAAACTGAAAAAAATGAAAAAGTGAAAAAGGTGAAAAATGAAAAACTTACCTGAAAAACTGAAAAAGAATGAAAAATGAAAAAAAAGGGTGAAAAATGAAAAATTCTTGAAAAATCTGAAAAAGTGAAAAATGAAAAACATGAAAAATTGAAAAAAGTGAAAAATGTGAAAAACCGGTGAAAAAACAGTTGAAAAAGATGAAAAAATTCTTATCCTATTTGAAAAATGAAAAACGATGAAAAACAATTGAAAAATTCGGCTTTGAAAAACTTTGAAAAAACGTGAAAAATTGAAAAAAGTGAAAAATATCTGAAAAACTGAAAAATGAAAAATGAAAAA"
	t := "TGAAAAATG"
	for i := 0; i < len(s)-len(t); i++ {
		//fmt.Println(s[i : i+4])
		if t == s[i:i+len(t)] {
			fmt.Print(i+1, " ")
		}
	}
}
